### ISSUE TITLE
Owncast Port 1935 not Open

### ISSUE THREAD

**Issue by barrythrew** [mother-of-all-self-hosting/mash-playbook#111]
It looks like the port is open UDP but not TCP, which is what RTMP uses.

Not possible to stream to the software.

**Comment by barrythrew** [comment]
Fixed with 

owncast_container_extra_arguments: ['-p 1935:1935/tcp']

in vars

**Comment by moan0s** [comment]
Thanks, I updated the role and streaming should now be fixed. Sorry for the hassle
