### ISSUE TITLE
Gitea cannot complete installation (empty user)

### ISSUE THREAD

**Issue by valmar** [mother-of-all-self-hosting/mash-playbook#164]
For reason explained in the README of the `defaults/main.yml` file, the `gitea_config_run_user` entry is left blank. However, when going to the installed gitea server, I am presented with an installation page, and I cannot proceed because the "Run as username" entry is empty, and also cannot be edited (see attached screenshot)

Thank you and keep up the good work!

![Screenshot from 2024-03-17 16-14-13](https://github.com/mother-of-all-self-hosting/mash-playbook/assets/558469/708451f3-5b01-4084-a2fe-c4fe9c3a8eab)

**Comment by Bergruebe** [comment]
I had the same problem. My solution was to manually add `git` as a user in the Initial Configuration.

If I remember correctly, the field was not enabled to edit, so I needed to remove the readonly html flag via the web inspector of my browser. I know not the perfect way, but it worked somehow.

Currently I'm trying to debug why Gitea cannot send mails via mash-exim-relay. It looks like Gitea is not in the same network with the exim-relay and the variable `gitea_container_additional_networks_custom` is not working to add Gitea to the `mash-exim-relay`-network.

**Comment by spantaleev** [comment]
I haven't done a new Gitea installation to confirm this yet. I suppose something may have changed on the Gitea side with regard to `gitea_config_run_user`.

-----

Or it may be that `gitea_uid` (derived from `mash_playbook_uid` via group vars) coincides with some `/etc/passwd` user inside the Gitea container.

Try `id -u mash` on the server and see what it reports. On 2 of my Gitea servers, `gitea_uid` happens to be `984` and `998`, which doesn't conflict with any existing user in the container's `/etc/passwd` file.

You can also grep for this uid in the output of `docker exec -it mash-gitea /bin/sh -c 'cat /etc/passwd'` and see if you have a match. The output currently looks like this:

```
root:x:0:0:root:/root:/bin/ash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/mail:/sbin/nologin
news:x:9:13:news:/usr/lib/news:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
operator:x:11:0:operator:/root:/sbin/nologin
man:x:13:15:man:/usr/man:/sbin/nologin
postmaster:x:14:12:postmaster:/var/mail:/sbin/nologin
cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
ftp:x:21:21::/var/lib/ftp:/sbin/nologin
sshd:x:22:22:sshd:/dev/null:/sbin/nologin
at:x:25:25:at:/var/spool/cron/atjobs:/sbin/nologin
squid:x:31:31:Squid:/var/cache/squid:/sbin/nologin
xfs:x:33:33:X Font Server:/etc/X11/fs:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
cyrus:x:85:12::/usr/cyrus:/sbin/nologin
vpopmail:x:89:89::/var/vpopmail:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
smmsp:x:209:209:smmsp:/var/spool/mqueue:/sbin/nologin
guest:x:405:100:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
git:x:1000:1000:Linux User,,,:/var/lib/gitea/git:/bin/bas
```

**Comment by valmar** [comment]
Thank you for your answer! So `id -u mash` gives me 989, but in the gitea container, `cat /etc/passwd | grep 989`  gives me nothing so I don't think there is a conflict

**Comment by spantaleev** [comment]
Yes, seems like there's no conflict. This probably means that something in Gitea has changed and that we may need to set `gitea_config_run_user: git` in all cases? Can you confirm that defining this extra variables fixes the problem for your new installation?

**Comment by valmar** [comment]
Thank you! Yes, I confirm this works!

**Comment by danrmiller** [comment]
> Yes, seems like there's no conflict. This probably means that something in Gitea has changed and that we may need to set `gitea_config_run_user: git` in all cases? Can you confirm that defining this extra variables fixes the problem for your new installation?

Confirmed here too.
