### ISSUE TITLE
Freshrss is not updating feeds

### ISSUE THREAD

**Issue by valmar** [mother-of-all-self-hosting/mash-playbook#174]
A freshrss server created following strictly these instructions: https://github.com/mother-of-all-self-hosting/mash-playbook/blob/main/docs/services/freshrss.md does not update feeds.

Looking at the ansible role, I see that it sets CRON_MIN: `CRON_MIN=2,32` That should trigger the update of the feed but that seems not to happen

**Comment by spantaleev** [comment]
From what I've heard others mention, cron doesn't work for some reason.

**Comment by valmar** [comment]
Ah, is this a general FreshRSS problem (not related to this playbook)? If yes, I will report the problem on their GitHub project.

Is there a suggested alternative? Perhaps running a cron job on the host triggering a `docker exec` in the container?

Thank you!

**Comment by valmar** [comment]
I solved the problem by running cron on the host, like explained here: 

https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#option-2-cron-on-the-host-machine

This works as a workaround until the underlying problem is investigated and resolved, therefore I will close the issue
