### ISSUE TITLE
TASK [galaxy/tandoor] has syntax errors

### ISSUE THREAD

**Issue by brysondev** [mother-of-all-self-hosting/mash-playbook#177]
Commands run: `git pull` & `just roles && just setup-all`

Output:

```
TASK [galaxy/tandoor : ansible.builtin.include_tasks] ***********************************************************************************************************************************************************
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected '-' indicator

The error appears to be in 'mash-playbook/roles/galaxy/tandoor/tasks/uninstall.yml': line 17, column 39, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      with_items:
        - {{ tandoor_identifier_api }}.service
                                      ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
error: Recipe `run` failed on line 99 with exit code 4
error: Recipe `run-tags` failed on line 103 with exit code 4
```

**Comment by sudo-Tiz** [comment]
I proposed a [PR](https://github.com/IUCCA/ansible-role-tandoor/pull/1)

**Comment by UehgxEQbFiw4Tlw8** [comment]
Hello everyone,

I can confirm, the patch is working, tested yesterday myself. Manual modification of the file.

But I have now  a further question: How can I prevent, next time I use just roles and just setup-all or similar, that the old version of the file with the syntax errors is downloaded again? Have you full control on the galaxy?

I made a backup copy of the corrected file uninstall.yml and I will look after the error with a diff and copy the correct one in the playbook every time I must make a change in the system with just... but this is more a manual workaround then a real solution, not satisfactory on the long term, I think you agree.

Btw., there is a similar issue with the file in roles/galaxy/nextcloud/defaults/main.yml if I correct remeber. Just tested with just roles etc.

Diff output:


```
< nextcloud_container_image_customizations_enabled: "{{ nextcloud_container_image_customizations_php_imagick_installation_enabled or nextcloud_container_image_customizations_samba_enabled or nextcloud_container_image_customizations_packages_to_install | length > 0 }}"

> nextcloud_container_image_customizations_enabled: |
>   {{
>     (
>       nextcloud_container_image_customizations_php_imagick_installation_enabled
>       or
>       nextcloud_container_image_customizations_samba_enabled
>       or
>       nextcloud_container_image_customizations_packages_to_install | length > 0
>     )
>   }}
139d147
< #nextcloud_container_image_final: "{{ nextcloud_container_image_customized if nextcloud_container_image_customizations_enabled else nextcloud_container_image }}"
140a149
> 
```

Wrong syntax is in the multiple lines (>), the solution is to write all in a single line (<; btw.there was also a second change in 139d147 in the meantime, see < # etc. etc., which I corrected also manually, commented juast the old line, just in case I forget something...).
I think, it is correlated to another issue in this project, but I cannot find which one now so quickly.

Thank you for the help and wonderful work done so far! 
Have a nice day.

Best
M.

**Comment by UehgxEQbFiw4Tlw8** [comment]
It was:

Unable to find image 'localhost/nextcloud:27.1.4-apache-customized' locally #127

**Comment by sudo-Tiz** [comment]
> I proposed a [PR](https://github.com/IUCCA/ansible-role-tandoor/pull/1)

Tag has to be created for the MR and added to requierements of mash

**Comment by spantaleev** [comment]
Fixed by https://github.com/mother-of-all-self-hosting/mash-playbook/pull/178
