### ISSUE TITLE
[Vaultwarden] Removing 'vaultwarden_config_admin_token' does not disable /admin

### ISSUE THREAD

**Issue by brysondev** [mother-of-all-self-hosting/mash-playbook#179]
The admin page is still accessible when this line is removed, and the script is re-run `just setup-all`

**Comment by brysondev** [comment]
`/mash/vaultwarden/data/config.json`
![image](https://github.com/mother-of-all-self-hosting/mash-playbook/assets/13501615/1fbbd294-a3ad-4a89-920d-f7f27535a602)

**Comment by spantaleev** [comment]
This is documented upstream, here: https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page

> The first time you save a setting in the admin page, config.json will be generated in your DATA_FOLDER. Values in this file will take precedence over the corresponding environment variable.

> Note: Removing the environment variable ADMIN_TOKEN won't disable the admin page if the value is persisted in the config.json file mentioned above. To disable admin page, make sure no ADMIN_TOKEN environment variable is set, and no "admin_token" key exists in config.json, if that file exists.

The playbook does not do anything special to help you with these manual tasks. It's somewhat unfortunate that Vaultwarden is persisting the `ADMIN_TOKEN` (and other such things, it seems) in a config file. Ideally, it wouldn't do this.

It may be possible to adjust the Vaultwarden role to remove lines matching `admin_token` from the `/mash/vaultwarden/data/config.json` file if the file exists and if `vaultwarden_config_admin_token` is currently empty.
