### ISSUE TITLE
How to add environment variable to calibre

### ISSUE THREAD

**Issue by mwelsch** [mother-of-all-self-hosting/mash-playbook#215]
I want to be able to convert ebooks with my calibre-web version. This is done by simply adding an environment variable to the container; copied from the calibre-web github:

Include the environment variable `DOCKER_MODS=linuxserver/mods:universal-calibre` in your Docker run/compose file to add the Calibre ebook-convert binary (x64 only). Omit this variable for a lightweight image.

(The binary `ebook-converter` is then placed in `/usr/bin` but it isn't there so my guess is that the variable is not set)

How can I add/configure this environment variable to the container via the playbook?

**Comment by spantaleev** [comment]
The https://github.com/lingawakad/ansible-role-calibre-web role does not contain an Ansible variable for adding additional environment variables. Most of the other MASH roles have such a variable, but this one is maintained by someone else and their role is not so extensible. Consider opening a Feature Request there.

**Comment by lingawakad** [comment]
> I want to be able to convert ebooks with my calibre-web version. This is done by simply adding an environment variable to the container; copied from the calibre-web github:
> 
> Include the environment variable `DOCKER_MODS=linuxserver/mods:universal-calibre` in your Docker run/compose file to add the Calibre ebook-convert binary (x64 only). Omit this variable for a lightweight image.
> 
> (The binary `ebook-converter` is then placed in `/usr/bin` but it isn't there so my guess is that the variable is not set)
> 
> How can I add/configure this environment variable to the container via the playbook?

Hey, i added support for Docker mods in PR #216 so this should now be possible. If you want to test before the PR is merged, you can manually change the version in ```requirements.txt``` to ```v0.6.21-1``` and add two lines to your host ```vars.yml```:
```
calibre_web_environment_variables_extension: |
  DOCKER_MODS=linuxserver/mods:universal-calibre
```
