### ISSUE TITLE
ansible connection issue ?

### ISSUE THREAD

**Issue by feydreva** [mother-of-all-self-hosting/mash-playbook#233]
Hello, 

i am having this issue and I don't know why.
I haven't upgraded in a few month. Since then I have my OS (Arch) reinstalled once because of a crash, but /home stayed intact, ssh key didn't change.

I am still using the same playbook. host and host_vars haven't changed since then.

I can access the server via ssh, no issue.

```
[feydreva@spychea mash-playbook]$ ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start
ERROR! couldn't resolve module/action 'ansible.posix.authorized_key'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/feydreva/mash-playbook/roles/galaxy/ssh/tasks/main.yml': line 3, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- block:
  - name: Add authorized keys
    ^ here
```

and my host file looks like that, and it used to work fine.
`[mash_servers]
mash.randome.camp ansible_host=65.108.54.140 ansible_ssh_user=feydreva become=true become_user=root ansible_python_interpreter=/usr/bin/python3
`

seems to be a ssh issue, but don't know why, where.
ansible is installed, python_passlib also, I don't know what else to look for.
Could you help ?

**Comment by spantaleev** [comment]
Arch (and possibly some other distros) split Ansible into 2 packages: `ansible-core` and `ansible`.

`ansible-core` only contains some core components, while `ansible` contains a bunch of extra modules/collections (like `ansible.posix.authorized_key`).

So.. maybe you don't have `ansible` and only have `ansible-core`?

**Comment by feydreva** [comment]
Hello, 

yes that was it, I just installed ansible-core. Installing ansible solved that issue
Thank you !
