### ISSUE TITLE
Update Authentik to latest version

### ISSUE THREAD

**Issue by Dimtuhop** [mother-of-all-self-hosting/mash-playbook#236]
The playbook and related ansible role are on version 2024.4.1, but version 2024.6.1 is the latest available version. 
This version has a few breaking changes listed: https://docs.goauthentik.io/docs/releases/2024.6

**Comment by spantaleev** [comment]
I've upgraded it.

Skimming through the release notes, it seems like it's just Postgres v14 not being support may cause trouble for some people. The playbook makes [upgrading Postgres](https://github.com/mother-of-all-self-hosting/mash-playbook/blob/main/docs/services/postgres.md#upgrading-postgresql) easy, so anyone that hits this problem should be able to follow the docs and get it solved.
