### ISSUE TITLE
# Issue on Outline version mismatch

### ISSUE THREAD

**Issue by neokyx** [mother-of-all-self-hosting/mash-playbook#248]
Hi and first of all, thank you for your amazing job !

I encountered an error when deploying Outline due to the mismatch of versions in files: 0.74.0-0 in "versions.md" and 0.74.0-0-0 (note the extra " -0" causing the issue) in "templates/requirements.yml", line 240, causing the playbook to fail when trying to pull the correct image during its execution.

I made a workaround for this by using a script which replace the wrong value in "requirements.yml" by the one in "versions.md" file before each `just update` command, and everything is fine after that.
 
Edit: the snippet is available here: https://shorter.me/outline

**Comment by spantaleev** [comment]
Thanks for reporting this! I have upgraded Outline to v0.78.0 and pushed that updated to MASH, which should fix the issue for you.

I have not tested the new v0.78.0 version, nor the upgrade path. Let us know if you hit any issues!
