### ISSUE TITLE
Vaultwarden 1.28.0 released

### ISSUE THREAD

**Issue by igogold** [mother-of-all-self-hosting/mash-playbook#25]
Please update playbook to use a new [1.28.0 release](https://github.com/dani-garcia/vaultwarden/releases/tag/1.28.0) of Vaultwarden server.

Also simple addition of var `vaultwarden_version: 1.28.0` doesn't work. `mash-vaultwarden.service` exits with an error, in the log:
```text
мар 29 10:13:53 mash systemd[1]: Starting Vaultwarden (mash-vaultwarden)...
мар 29 10:13:54 mash mash-vaultwarden[1567406]: 9c9b3eddd1afcd635187f5486762da020d983b1ab0639861726bfd2abc7486e8
мар 29 10:13:54 mash systemd[1]: Started Vaultwarden (mash-vaultwarden).
мар 29 10:13:55 mash mash-vaultwarden[1567491]: /start.sh: exec: line 25: /vaultwarden: Operation not permitted
мар 29 10:13:55 mash systemd[1]: mash-vaultwarden.service: Main process exited, code=exited, status=126/n/a
мар 29 10:13:55 mash systemd[1]: mash-vaultwarden.service: Failed with result 'exit-code'.
мар 29 10:14:25 mash systemd[1]: mash-vaultwarden.service: Scheduled restart job, restart counter is at 1.
мар 29 10:14:25 mash systemd[1]: Stopped Vaultwarden (mash-vaultwarden).
```
It seems docker `--cap-drop=ALL` option is the root of this issue. But on 1.27.0 it works well.

After removing `--cap-drop=ALL` line from service template the container run successfully. This is a workaround, not a fix though.

**Comment by spantaleev** [comment]
The permission problems are related to https://github.com/dani-garcia/vaultwarden/issues/3386

Our Ansible role includes a workaround which adds the additional `NET_BIND_SERVICE` capability. When/if the upstream issue gets resolved, we'll be able to drop it.
