### ISSUE TITLE
FAIL - Adjust Nextcloud configuration values related to preview generator

### ISSUE THREAD

**Issue by UehgxEQbFiw4Tlw8** [mother-of-all-self-hosting/mash-playbook#258]
Hi!
The problem: after updating the system with just roles && just setup-all, after modifying my vars.yml with the line set to "true" as in the documentation and after installing the App, running just run-tags adjust-nextcloud-config breaks with message:

TASK [galaxy/nextcloud : Adjust Nextcloud configuration values related to preview generator] ***************************************************************
changed: [mash.example.com] => (item={'appType': 'config:system:set', 'appConfig': '', 'configName': 'preview_max_x', 'type': 'string', 'value': None})
changed: [mash.example.com] => (item={'appType': 'config:system:set', 'appConfig': '', 'configName': 'preview_max_y', 'type': 'string', 'value': None})
failed: [mash.example.com] (item={'appType': 'config:app:set', 'appConfig': 'preview', 'configName': 'jpeg_quality', 'type': 'int', 'value': 80}) => changed=true 
  ansible_loop_var: item
  cmd:
  - docker
  - exec
  - --user=998:1002
  - mash-nextcloud-server
  - php
  - /var/www/html/occ
  - config:app:set
  - --type=int
  - --value=80
  - --
  - preview
  - jpeg_quality
  delta: '0:00:01.139061'
  end: '2024-09-14 12:29:06.329837'
  item:
    appConfig: preview
    appType: config:app:set
    configName: jpeg_quality
    type: int
    value: 80
  msg: non-zero return code
  rc: 1
  start: '2024-09-14 12:29:05.190776'
  stderr: |2-
  
    In AppConfig.php line 1069:
  
      Unknown type int
  
  
    config:app:set [--output [OUTPUT]] [--value VALUE] [--type TYPE] [--lazy|--no-lazy] [--sensitive|--no-sensitive] [--update-only] [--] <app> <name>
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

As you can see, some ints seems to be unknown (how can that be?) but required or set that way in the 3rd line above (I think this is (?) the problem).

Any help or idea to solve the issue please? Highly appreciated, thank you very much!

Have a nice day and weekend!

Kind regards,
M.

**Comment by neokyx** [comment]
Same issue here, since several Nextcloud versions.

**Comment by sudo-Tiz** [comment]
Solved in [ansible-role-nextcloud](https://github.com/mother-of-all-self-hosting/ansible-role-nextcloud/pull/24) v30.0.0-1
Upgrading MASH should fix your issues
