### ISSUE TITLE
Run service (nextcloud) under multiple domains

### ISSUE THREAD

**Issue by EconomicTouristsArmLate** [mother-of-all-self-hosting/mash-playbook#262]
I have an existing nextcloud installation i want to migrate over to a mash host.
That nextcloud is currently served under multiple domains (cloud.foo.com, cloud.bar.com).
To do that, I currently have
- 2 CNAMEs pointing to the host
- 2 reverse-proxy vhosts (i'm using nginx) with one domain in `server_name` each
- added both domains to `trusted_domains` in nextcloud's `config.php`

Is this supported by mash?
If not, would you be willing to support that use case, eg if there is a contribution for adding that feature to the nextcloud role?
Can you give some pointers what would need changing?

Thanks for maintaining mash, it's great!

**Comment by spantaleev** [comment]
Our Ansible role for Nextcloud does not configure `trusted_domains`, so you can set that yourself to contain multiple values.

Where you don't currently see cooperation from the Ansible role is in its integration with Traefik. `nextcloud_container_labels_traefik_rule` [currently only deals with 1 hostname](https://github.com/mother-of-all-self-hosting/ansible-role-nextcloud/blob/110526f68e86bad9b748583dd088bc5458adf634/defaults/main.yml#L182).

You should be able to override this variable in your own `vars.yml` file like this:

```diff
-nextcloud_container_labels_traefik_rule: "Host(`{{ nextcloud_container_labels_traefik_hostname }}`){% if nextcloud_container_labels_traefik_path_prefix != '/' %} && PathPrefix(`{{ nextcloud_container_labels_traefik_path_prefix | quote }}`){% endif %}"
+nextcloud_container_labels_traefik_rule: "(Host(`{{ nextcloud_container_labels_traefik_hostname }}`) || Host(`your_2nd_hostname_here`)){% if nextcloud_container_labels_traefik_path_prefix != '/' %} && PathPrefix(`{{ nextcloud_container_labels_traefik_path_prefix | quote }}`){% endif %}"
```

Note that the `nextcloud_hostname` variable still influences other things:

- like the `nextcloud_url` variable which influences the `overwrite.cli.url` setting
- [some](https://github.com/mother-of-all-self-hosting/ansible-role-nextcloud/blob/110526f68e86bad9b748583dd088bc5458adf634/defaults/main.yml#L231-L240) redirect middlewares (`nextcloud_container_labels_traefik_http_middlewares_default`) - if you need these for the 2nd domain, you can inject something similar via `nextcloud_container_labels_traefik_http_middlewares_custom`

------

Serving Nextcloud at 2 multiple domains is likely not something that many people wish to do, so it's not something we directly care about supporting. If there's a nice clean PR that adds support and doesn't overcomplicate things, we're not against accepting it.

**Comment by EconomicTouristsArmLate** [comment]
Great, thank you!  I'll try it in the next few days.
If it can be set up via 2-3 variables, it's fine to me to maintain it like that.
And I agree that supporting multiple domains is likely scope creep for this playbook, so I won't send a PR for now.
