### ISSUE TITLE
Peertube 6.3

### ISSUE THREAD

**Issue by Beryesa** [mother-of-all-self-hosting/mash-playbook#264]
A new release is out!
But it needs a migration step, would we do it manually?
https://joinpeertube.org/news/release-6.3
https://github.com/Chocobozzz/PeerTube/releases/tag/v6.3.0
(Thanks!)

**Comment by spantaleev** [comment]
The migration steps have been automated as part of https://github.com/mother-of-all-self-hosting/ansible-role-peertube/commit/32c308689f954e6e385cc7a5c0d49e04d30e5ac0, so upgrading should be as simple as re-running the playbook.
