### ISSUE TITLE
Just roles does not update Nextcloud to 29.0.7

### ISSUE THREAD

**Issue by UehgxEQbFiw4Tlw8** [mother-of-all-self-hosting/mash-playbook#265]
Hello,

Nextcloud should be now available as tag 29.0.7 - see Docker Hub - just roles gives me right now 29.0.6 back:

- extracting nextcloud to /home/username/mash-playbook/roles/galaxy/nextcloud
- nextcloud (v29.0.6-0) was installed successfully

On Docker Hub there is also a 30.0.0. tag. (last pushed two days ago).

Thank you.

Kind regards,
M.

**Comment by UehgxEQbFiw4Tlw8** [comment]
Hello,

just FYI: installation work also with 30.0.0 - just finished to test fixing the tag in my vars.yml with nextcloud_version - even on a RaspberryPi 4 seems to work. Only a warning find so far about an EXTRA FILE on the server which should not be required anymore but it is still there:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- nextcloud-init-sync.lock

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [nextcloud-init-sync.lock] => Array
                        (
                            [expected] => 
                            [current] => cf83e1357e****************************************************** etc. etc.
                        )

                )

        )

)

The file is in /mash/nextcloud/data:
-rw-r--r--  1 mash mash       0 21. Sep 15:11 nextcloud-init-sync.lock

or at least is the only one I could find.

In case of problems, follow the official documentation here:
https://docs.nextcloud.com/server/30/admin_manual/issues/code_signing.html
for a solution.

Best regards,
M.

**Comment by spantaleev** [comment]
`29.0.7` was very slow to get published as a container image. We had upgraded the playbook to try and pull `29.0.7` a few times, only to revert it later.

I've upgraded it to 30.0.0 now.

------

About this extra `nextcloud-init-sync.lock` file (my installation has it too), it seems like it's related to this upstream issue: https://github.com/nextcloud/docker/issues/2070
