### ISSUE TITLE
Typo in mariadb root password variable

### ISSUE THREAD

**Issue by twity1337** [mother-of-all-self-hosting/mash-playbook#303]
There is a typo in the variable name `mariadb_root_passsword`  (written with 3 s).
See the documentation for reference: https://github.com/mother-of-all-self-hosting/mash-playbook/blob/main/docs/services/mariadb.md 

It's not just a typo in the documentation, but also in code. The playbook needs to have the misspelled variable set.

**Comment by spantaleev** [comment]
Good catch! Thanks!
