### ISSUE TITLE
Peertube v7.0

### ISSUE THREAD

**Issue by Beryesa** [mother-of-all-self-hosting/mash-playbook#326]
Peertube 7 introduces a complete makeover https://joinpeertube.org/news/release-7.0
https://github.com/Chocobozzz/PeerTube/releases/tag/v7.0.0
No extra migration this time
(Thanks!)

**Comment by spantaleev** [comment]
The playbook has already been updated to PeerTube v7, 4 days ago. See 6c0bd334fc72e7c1d3d0d37591700d9c76864075

**Comment by Beryesa** [comment]
Oh, that seems to be the case, VERSIONS.md misled me, now I see, thanks.
