### ISSUE TITLE
Mobilizon returns 502 Bad Gateway

### ISSUE THREAD

**Issue by oliverlorenz** [mother-of-all-self-hosting/mash-playbook#97]
Hello!

I am trying to run a mobilizon on my server. Unfortunately, even with a fresh installation I only get a 502, but unfortunately I can't see what I'm doing wrong. My configuration:

```
mash_playbook_generic_secret_key: ***
mash_playbook_docker_installation_enabled: true
devture_docker_sdk_for_python_installation_enabled: true
devture_timesync_installation_enabled: true
mash_playbook_reverse_proxy_type: playbook-managed-traefik
devture_traefik_config_certificatesResolvers_acme_email: ***
mobilizon_enabled: true
mobilizon_hostname: events.***.com
```

Can somebody give me a hint?

**Comment by oliverlorenz** [comment]
I found one thing that solved my problem with the 503. Even though I am now facing another problem, I wanted to share that I have added some parameter:

```
########################################################################
#                                                                      #
# postgis                                                              #
#                                                                      #
########################################################################

postgis_enabled: true

# Put a strong password below, generated with `pwgen -s 64 1` or in another way
postgis_connection_password: ******

########################################################################
#                                                                      #
# /postgis                                                             #
#                                                                      #
########################################################################
```
This is also mentioned indirectly via the dependencies, but I have missed it. Perhaps this should be included in the sample configuration for mobilizon

**Comment by spantaleev** [comment]
None of the sample configs for services include dependencies. It's unfortunate that you've missed it though - I wonder if we can make dependencies more prominent somehow.

**Comment by oliverlorenz** [comment]
I don't really have a good idea. I would just close the issue now. If someone runs into a similar problem, it is now at least documented here :)
